### ISSUE TITLE
Module is not available as hook module

### ISSUE THREAD

**Issue by ghost** [jamiroconca/crpTag#1]
For example in the module content there is no provider of crpTag to put into the subscriber arrea of content.

Reason:

I think it will not be registered after installation...

PS: With Zikula 1.3.2

**Comment by ghost** [comment]
@jamiroconca 
Hi, I did start to work on this module. Do you want to work with it again or is it ok for you, that I work on it with my own forked repository?

Please give feedback!

**Comment by jamiroconca** [comment]
hi
zikula and related works are currently (and probably, will be in the future) not in my todo list, so feel free to work on your own repository

**Comment by ghost** [comment]
Thx for your reply.
